version: 2
updates:
  # Backend: Python (Poetry)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
      - "backend"

  # Frontend: npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
      - "frontend" 