[phases.setup]
nixPkgs = ["poetry"]

[phases.install]
cmds = ["poetry install --no-dev"]

[phases.build]
cmds = ["poetry run python -c 'import sys; print(sys.version)'"]

[start]
cmd = "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT" 