[phases.setup]
nixPkgs = ["poetry"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "poetry install --only main"
]

[start]
cmd = "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT" 